### ISSUE TITLE
Incompatibility with Contributte console

### ISSUE THREAD

**Issue by patrickkusebauch** [wavevision/nette-tests#12]
This gets created in the DI container when both packages are loaded:

```php
	public function createServiceHttp__request(): Wavevision\NetteTests\Mocks\RequestMock
	{
		return new Nette\Http\Request(new Nette\Http\UrlScript('https://www.localhost.net'));
	}
```

This library requires the return type, but contributte/console does provide something else with their extension:
```php
		// Setup URL for CLI
		if ($config->url !== null && $builder->hasDefinition('http.request')) {
			/** @var ServiceDefinition $httpDef */
			$httpDef = $builder->getDefinition('http.request');
			$httpDef->setFactory(Request::class, [new Statement(UrlScript::class, [$config->url])]);
		}
```

**Comment by jfilla** [comment]
Thank you for your report. It's a known bug in contributte/console. See https://github.com/contributte/console/pull/43. Remove console.url from your test config.neon as a temporary fix.

**Comment by mabar** [comment]
Hey guys, sorry for that. Since I left the organization, I don't really want solve their issues. Hovever, I solved that issue in https://github.com/orisai/nette-console, only request factory is overriden by console.

**Comment by f3l1x** [comment]
Hi @jfilla @patrickkusebauch already in upstream, thank you for your time & work.

https://github.com/contributte/console/commit/00a6b35a46ea66d296ebf13d099f14a1f29f1388
